### ISSUE TITLE
Issue #1: User can view anime through a list of categories

### ISSUE THREAD

**Issue by TreMitchell** [TreMitchell/front-end-project-rc1024#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="915" alt="Screenshot 2024-11-27 at 9 06 34 AM" src="https://github.com/user-attachments/assets/906e16fd-808b-43d3-94f9-a9dd4567c67e">
<img width="275" alt="Screenshot 2024-11-27 at 9 07 52 AM" src="https://github.com/user-attachments/assets/9eb66940-eb19-4950-8b69-991f5fb45d59">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] In the html, Get started with adding the navigation bar showing similarity to the wireframe above.
- [x] Add a search bar for adding the potential use case of searching for an anime.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
