### ISSUE TITLE
Issue #2: User can search an anime

### ISSUE THREAD

**Issue by TreMitchell** [TreMitchell/front-end-project-rc1024#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![IMG_1722](https://github.com/user-attachments/assets/d2a8478c-63ff-456e-b914-d65818c55118)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x]  Define a search feature inside of the HTML.
- [x]  Add view swapping so you can switch from the homepage to the "search results" page.
- [x]  Call the API's search option to get the different types of search results within the conditions.
- [x]  Create a view and tab function inside the main.ts so view swapping  can occur, 
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
