### ISSUE TITLE
Issue #3: User can see a description of what the anime is

### ISSUE THREAD

**Issue by TreMitchell** [TreMitchell/front-end-project-rc1024#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![IMG_1723](https://github.com/user-attachments/assets/7087168c-4a35-4407-b084-7af9d7b347b0)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a container div to place all of the anime-details inside.
- [x] Create an anime-details that includes the title and the description of the searched for anime.
- [x] Include the thumbnail of the anime.
- [x] In main.ts, make a function for the displayed/selected anime.
- [x] Make a new tab/view so it can be swapped without affecting either the homepage or the search results.
- [x] Connect the tab view from main.ts to anime-details.
- [x] When searching for a new anime, make sure the previous anime search is cleared out.
- [ ] Provide more CSS styling for the container to potentially make it bigger with more space as seen in the mockup wireframe.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
