### ISSUE TITLE
Issue #4: User can like an anime

### ISSUE THREAD

**Issue by TreMitchell** [TreMitchell/front-end-project-rc1024#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![IMG_1724](https://github.com/user-attachments/assets/394472e2-1a3b-4782-8509-dc56353da895)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Find a free heart or star icon in favicon.
- [ ] Apply the icon to the top left of the anime container.
- [ ] Make a click function in main.ts to where once clicked, it will display a different color of the icon.
- [ ] Create a new viewpoint to view the possible liked anime.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] EXTRA  FEATURE/ISSUE: Make the homepage of the project functionable.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
